Repository netgrif/application-engine, pull requests merged in 2022-12, with the labels that each got.

#146 Release/6.2.5
  CHANGELOG.md
  pom.xml
  src/main/groovy/com/netgrif/application/engine/AsyncRunner.groovy
  src/main/java/com/netgrif/application/engine/auth/domain/LoggedUser.java
  src/main/java/com/netgrif/application/engine/configuration/AbstractSecurityConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/NaeSecurityConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/properties/SecurityConfigProperties.java
  src/main/java/com/netgrif/application/engine/configuration/security/PublicAuthenticationFilter.java
  src/main/java/com/netgrif/application/engine/configuration/security/jwt/JwtService.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticTaskService.java
  src/main/java/com/netgrif/application/engine/elastic/service/executors/Executor.java
  src/main/java/com/netgrif/application/engine/elastic/web/requestbodies/CaseSearchRequest.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/fieldbuilder/TextFieldBuilder.java
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  src/main/java/com/netgrif/application/engine/petrinet/web/PetriNetController.java
  src/main/java/com/netgrif/application/engine/workflow/service/EventService.java
  src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IWorkflowService.java
  src/test/groovy/com/netgrif/application/engine/action/FilterApiTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/service/CachePetriNetServiceTest.groovy
  src/test/resources/insurance_portal_demo_test.xml
Labels: Extra Large, release

#151 Release/6.2.5
  CHANGELOG.md
  pom.xml
  src/main/groovy/com/netgrif/application/engine/AsyncRunner.groovy
  src/main/java/com/netgrif/application/engine/auth/domain/LoggedUser.java
  src/main/java/com/netgrif/application/engine/configuration/AbstractSecurityConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/NaeSecurityConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/properties/SecurityConfigProperties.java
  src/main/java/com/netgrif/application/engine/configuration/security/PublicAuthenticationFilter.java
  src/main/java/com/netgrif/application/engine/configuration/security/jwt/JwtService.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticTaskService.java
  src/main/java/com/netgrif/application/engine/elastic/service/executors/Executor.java
  src/main/java/com/netgrif/application/engine/elastic/web/requestbodies/CaseSearchRequest.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/fieldbuilder/TextFieldBuilder.java
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  src/main/java/com/netgrif/application/engine/petrinet/web/PetriNetController.java
  src/main/java/com/netgrif/application/engine/workflow/service/EventService.java
  src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IWorkflowService.java
  src/test/groovy/com/netgrif/application/engine/action/FilterApiTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/service/CachePetriNetServiceTest.groovy
  src/test/resources/insurance_portal_demo_test.xml
Labels: Medium, release

#153 [NAE-1801] Change DataService
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/test/groovy/com/netgrif/application/engine/workflow/ChangedFieldsAllowedNetsTest.groovy
Labels: Extra Small

#154 Release/6.2.6
  CHANGELOG.md
  pom.xml
  src/main/java/com/netgrif/application/engine/petrinet/web/PublicPetriNetController.java
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/test/groovy/com/netgrif/application/engine/workflow/ChangedFieldsAllowedNetsTest.groovy
Labels: Extra Small, release

#155 Release/6.2.6
  CHANGELOG.md
  pom.xml
  src/main/java/com/netgrif/application/engine/petrinet/web/PublicPetriNetController.java
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/test/groovy/com/netgrif/application/engine/workflow/ChangedFieldsAllowedNetsTest.groovy
Labels: Extra Small

#157 [NAE-1806] Anonymous user password might not be 'null'
  src/main/java/com/netgrif/application/engine/auth/domain/AnonymousUser.java
  src/main/java/com/netgrif/application/engine/auth/domain/LoggedUser.java
Labels: bugfix, Extra Small

#159 Release/6.2.7
  CHANGELOG.md
  src/main/java/com/netgrif/application/engine/auth/domain/AnonymousUser.java
  src/main/java/com/netgrif/application/engine/auth/domain/LoggedUser.java
Labels: Extra Small, release

#148 [NAE-1793] Security filter for HTTP headers validation
  src/main/java/com/netgrif/application/engine/configuration/NaeSecurityConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/properties/Headers.java
  src/main/java/com/netgrif/application/engine/configuration/properties/SecurityConfigProperties.java
  src/main/java/com/netgrif/application/engine/configuration/security/filter/HostValidationRequestFilter.java
  src/test/groovy/com/netgrif/application/engine/workflow/ChangedFieldsAllowedNetsTest.groovy
Labels: Extra Small

#149 [NAE-1794] Configurable security headers
  src/main/java/com/netgrif/application/engine/auth/web/requestbodies/ChangePasswordRequest.java
  src/main/java/com/netgrif/application/engine/configuration/AbstractSecurityConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/NaeSecurityConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/properties/Headers.java
  src/main/java/com/netgrif/application/engine/configuration/properties/enumeration/HSTS.java
  src/main/java/com/netgrif/application/engine/configuration/properties/enumeration/XFrameOptionsMode.java
  src/main/java/com/netgrif/application/engine/configuration/properties/enumeration/XXSSProtection.java
  src/main/java/com/netgrif/application/engine/configuration/security/filter/HostValidationRequestFilter.java
  src/main/resources/application.properties
  src/test/groovy/com/netgrif/application/engine/workflow/ChangedFieldsAllowedNetsTest.groovy
Labels: Large
