Repository netgrif/application-engine, pull requests merged in 2022-03, with the labels that each got.

#14 [NAE-1577] Task reffed change behavior does not propagate - correction
  src/main/java/com/netgrif/application/engine/petrinet/domain/DataGroup.java
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/DataGroup.java
  src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/DataGroupsResource.java
  src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/eventoutcomes/LocalisedGetDataGroupsEventOutcome.java
Labels: bugfix, Extra Small

#15 [NAE-1588] DefaultFiltersRunner creates new cases every time
  src/main/groovy/com/netgrif/application/engine/startup/DefaultFiltersRunner.groovy
Labels: bugfix, Small

#19 Release 6.0.2
  .github/config.yml
  CHANGELOG.md
  pom.xml
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/groovy/com/netgrif/application/engine/startup/DefaultFiltersRunner.groovy
  src/main/java/com/netgrif/application/engine/importer/service/Importer.java
  src/main/java/com/netgrif/application/engine/orgstructure/groups/NextGroupService.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/DataGroup.java
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/main/java/com/netgrif/application/engine/workflow/service/FilterImportExportService.java
  src/main/java/com/netgrif/application/engine/workflow/service/MenuImportExportService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IFilterImportExportService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IMenuImportExportService.java
  src/main/java/com/netgrif/application/engine/workflow/web/PublicWorkflowController.java
  src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/DataGroup.java
  src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/DataGroupsResource.java
  src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/eventoutcomes/LocalisedGetDataGroupsEventOutcome.java
  src/test/groovy/com/netgrif/application/engine/importer/ImporterTestGroovy.groovy
  src/test/resources/this_kw_test.xml
Labels: bugfix, improvement, Large, release

#21 [NAE-1593] Remove user does not remove group from user groups
  src/main/java/com/netgrif/application/engine/orgstructure/groups/NextGroupService.java
Labels: bugfix, Extra Small

#22 [NAE-1590] Taskref with file field must be assigned
  src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/ITaskService.java
  src/main/java/com/netgrif/application/engine/workflow/web/AbstractTaskController.java
  src/main/java/com/netgrif/application/engine/workflow/web/PublicTaskController.java
  src/main/java/com/netgrif/application/engine/workflow/web/TaskController.java
Labels: bugfix, Small

#20 [NAE-1589] Role changes for logged users don't take effect
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/java/com/netgrif/application/engine/auth/service/AbstractUserService.java
  src/main/java/com/netgrif/application/engine/auth/service/UserDetailsServiceImpl.java
  src/main/java/com/netgrif/application/engine/auth/web/AuthenticationController.java
  src/main/java/com/netgrif/application/engine/auth/web/UserController.java
  src/main/java/com/netgrif/application/engine/configuration/SecurityConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/security/SecurityContextFilter.java
  src/main/java/com/netgrif/application/engine/orgstructure/groups/NextGroupService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/ProcessRoleService.java
  src/main/java/com/netgrif/application/engine/security/service/ISecurityContextService.java
  src/main/java/com/netgrif/application/engine/security/service/SecurityContextService.java
  src/test/groovy/com/netgrif/application/engine/auth/SecurityContextTest.groovy
Labels: bugfix, Medium

#26 [NAE-1618] SpringFox swagger failing in combination with spring actuator
  pom.xml
  src/main/java/com/netgrif/application/engine/configuration/SwaggerConfiguration.java
Labels: Medium

#24 [NAE-1600] Parallel auto-trigger tasks
  src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
Labels: bugfix, Extra Small

#25 [NAE-1614] Advanced search substring query
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
Labels: bugfix, Extra Small
