Repository netgrif/application-engine, pull requests merged in 2022-09, with the labels that each got.

#61 [NAE-1631] Process download in workflow view
  src/main/java/com/netgrif/application/engine/auth/domain/repositories/AuthorityRepository.java
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  src/main/java/com/netgrif/application/engine/petrinet/web/PetriNetController.java
Labels: improvement, Extra Small

#71 [NAE-1606] Configuration of case creation button from menu item
  src/main/resources/petriNets/engine-processes/preference_filter_item.xml
Labels: improvement, Small

#90 [NAE-1694] ProcessRoleService.findByImportId doesn't return list of process roles
  src/main/groovy/com/netgrif/application/engine/startup/AnonymousRoleRunner.groovy
  src/main/groovy/com/netgrif/application/engine/startup/DefaultRoleRunner.groovy
  src/main/groovy/com/netgrif/application/engine/startup/ImportHelper.groovy
  src/main/java/com/netgrif/application/engine/auth/service/AbstractUserService.java
  src/main/java/com/netgrif/application/engine/importer/service/Importer.java
  src/main/java/com/netgrif/application/engine/ldap/service/LdapGroupRefService.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/roles/ProcessRoleRepository.java
  src/main/java/com/netgrif/application/engine/petrinet/service/ProcessRoleService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IProcessRoleService.java
  src/test/groovy/com/netgrif/application/engine/action/AssignActionTest.groovy
  src/test/groovy/com/netgrif/application/engine/action/RemoveActionTest.groovy
  src/test/groovy/com/netgrif/application/engine/auth/TaskAuthorizationServiceTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/ActionRefTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/EventTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FieldTest.groovy
  src/test/java/com/netgrif/application/engine/petrinet/service/ProcessRoleServiceTest.java
  src/test/java/com/netgrif/application/engine/workflow/web/VariableArcsTest.java
Labels: bugfix, Large

#85 [NAE-1668] PDF Generator 2022 Summer Update
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/java/com/netgrif/application/engine/pdf/generator/config/PdfProperties.java
  src/main/java/com/netgrif/application/engine/pdf/generator/domain/PdfI18nDividerField.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfDataHelper.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfDrawer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfGenerator.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/fieldbuilder/I18nDividerFieldBuilder.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/interfaces/IPdfDrawer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/BooleanFieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/DataGroupFieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/EnumerationRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/FieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/I18nDividerFieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/MultiChoiceRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/SelectionFieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/TextFieldRenderer.java
  src/main/resources/application.properties
  src/main/resources/pdfGenerator/fonts/OpenSansCondensed-Bold.ttf
  src/main/resources/pdfGenerator/fonts/OpenSansCondensed-Light.ttf
  src/main/resources/pdfGenerator/fonts/Roboto-Bold.ttf
  src/main/resources/pdfGenerator/fonts/Roboto-Light.ttf
  src/main/resources/pdfGenerator/fonts/SourceCodePro-Light.ttf
  src/main/resources/pdfGenerator/fonts/SpaceMono-Bold.ttf
  src/main/resources/pdfGenerator/fonts/SpaceMono-Regular.ttf
Labels: improvement, Medium

#98 [NAE-1626] Trigger of set event for fileList value deletion is not implemented
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IDataService.java
  src/main/java/com/netgrif/application/engine/workflow/web/AbstractTaskController.java
  src/main/java/com/netgrif/application/engine/workflow/web/PublicTaskController.java
  src/main/java/com/netgrif/application/engine/workflow/web/TaskController.java
  src/test/groovy/com/netgrif/application/engine/workflow/TaskControllerTest.groovy
  src/test/resources/petriNets/all_data_refs.xml
Labels: bugfix, Small

#92 [NAE-1696] PDF Generator - legacy and flow layout
  CHANGELOG.md
  src/main/java/com/netgrif/application/engine/configuration/authentication/providers/ldap/UserDetailsContextMapperImpl.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfDataHelper.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfDrawer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/fieldbuilder/FieldBuilder.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/interfaces/IPdfDrawer.java
  src/main/java/com/netgrif/application/engine/workflow/web/TaskController.java
  src/test/resources/flow.xml
Labels: bugfix, Small

#88 [NAE-1679] User list frontend component
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/UserFieldValue.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/UserListField.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/UserListFieldValue.groovy
  src/main/java/com/netgrif/application/engine/elastic/domain/UserListField.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseMappingService.java
  src/main/java/com/netgrif/application/engine/export/service/ExportService.java
  src/main/java/com/netgrif/application/engine/importer/service/FieldFactory.java
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
  src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IDataService.java
  src/main/resources/application.properties
  src/test/groovy/com/netgrif/application/engine/auth/TaskAuthorizationServiceTest.groovy
  src/test/groovy/com/netgrif/application/engine/auth/WorkflowAuthorizationServiceTest.groovy
  src/test/groovy/com/netgrif/application/engine/elastic/DataSearchRequestTest.groovy
  src/test/groovy/com/netgrif/application/engine/permissions/ElasticSearchViewPermissionTest.groovy
  src/test/groovy/com/netgrif/application/engine/permissions/QueryDSLViewPermissionTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FieldTest.groovy
  src/test/groovy/com/netgrif/application/engine/workflow/UserRefsTest.groovy
Labels: improvement, new feature, Medium

#97 [NAE-1625] PetriNetService cache
  src/main/groovy/com/netgrif/application/engine/migration/MigrationOrderedCommandLineRunner.groovy
  src/main/java/com/netgrif/application/engine/configuration/CacheConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/NaeCacheResolver.java
  src/main/java/com/netgrif/application/engine/configuration/properties/CacheProperties.java
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IPetriNetService.java
  src/main/resources/application-dev.properties
  src/test/groovy/com/netgrif/application/engine/TestHelper.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/service/CachePetriNetServiceTest.groovy
Labels: improvement, Medium

#104 [NAE-1720] PDF number field is not null
  src/main/java/com/netgrif/application/engine/pdf/generator/service/fieldbuilder/TextFieldBuilder.java
Labels: bugfix, Extra Small

#106 Release 6.2.1
  CHANGELOG.md
  pom.xml
  src/main/java/com/netgrif/application/engine/pdf/generator/service/fieldbuilder/TextFieldBuilder.java
Labels: Extra Small

#107 [NAE-1714] Parameter processIdentifier v classe CaseSearchRequest
  src/main/java/com/netgrif/application/engine/elastic/web/requestbodies/CaseSearchRequest.java
Labels: Extra Small

#101 [NAE-1693] TaskController deleteFile endpoint lacks data about tasks
  pom.xml
  src/main/java/com/netgrif/application/engine/workflow/web/PublicTaskController.java
  src/main/java/com/netgrif/application/engine/workflow/web/TaskController.java
Labels: bugfix, improvement, Extra Small

#115 Release 6.2.2
  .github/config.yml
  CHANGELOG.md
  pom.xml
  src/main/java/com/netgrif/application/engine/elastic/web/requestbodies/CaseSearchRequest.java
  src/main/java/com/netgrif/application/engine/workflow/web/PublicTaskController.java
  src/main/java/com/netgrif/application/engine/workflow/web/TaskController.java
Labels: Extra Small, release
