Repository netgrif/application-engine, pull requests merged in 2022-05, with the labels that each got.

#55 [NAE-1621] Required data group layout tag if layout type is “grid”
  pom.xml
  src/main/groovy/com/netgrif/application/engine/startup/FinisherRunner.groovy
  src/main/java/com/netgrif/application/engine/importer/service/Importer.java
  src/test/groovy/com/netgrif/application/engine/auth/TaskAuthorizationServiceTest.groovy
  src/test/groovy/com/netgrif/application/engine/auth/WorkflowAuthorizationServiceTest.groovy
  src/test/java/com/netgrif/application/engine/auth/service/LdapTest.java
  src/test/java/com/netgrif/application/engine/importer/ImporterTest.java
  src/test/resources/invalid_data_ref_layout.xml
  src/test/resources/test-server.ldif
Labels: Large

#57 Release 6.0.5
  CHANGELOG.md
  pom.xml
  src/main/groovy/com/netgrif/application/engine/startup/FinisherRunner.groovy
  src/main/java/com/netgrif/application/engine/importer/service/Importer.java
  src/test/groovy/com/netgrif/application/engine/auth/TaskAuthorizationServiceTest.groovy
  src/test/groovy/com/netgrif/application/engine/auth/WorkflowAuthorizationServiceTest.groovy
  src/test/java/com/netgrif/application/engine/auth/service/LdapTest.java
  src/test/java/com/netgrif/application/engine/importer/ImporterTest.java
  src/test/resources/invalid_data_ref_layout.xml
  src/test/resources/test-server.ldif
Labels: Large

#39 [NAE-1477] New pdfgeneration action in actionDelegate
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/test/groovy/com/netgrif/application/engine/pdf/service/PdfGeneratorTest.groovy
Labels: Extra Small

#60 [NAE-1636] resolveTaskRefOrderOnGrid with forbidden dataField
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
Labels: bugfix, Extra Small

#62 [NAE-1637] PDF generator with template does not work
  src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfGenerator.java
Labels: bugfix, Extra Small

#40 [NAE-1478] ActionDelegate functions overloading
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/test/groovy/com/netgrif/application/engine/pdf/service/PdfGeneratorTest.groovy
  src/test/resources/all_data_pdf.xml
Labels: improvement, Small

#46 [NAE-1049] Case name doesn't change
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/ITaskService.java
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/dataset/ChangeCasePropertyTest.groovy
  src/test/resources/case_name_change_test.xml
Labels: bugfix, Large

#64 [NAE-1562] Improved logging of deleting resources
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
  src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
Labels: Extra Small

#59 [NAE-1521] Authentication Providers
  pom.xml
  src/main/java/com/netgrif/application/engine/auth/service/AfterRegistrationAuthService.java
  src/main/java/com/netgrif/application/engine/auth/service/UserService.java
  src/main/java/com/netgrif/application/engine/auth/service/interfaces/IAfterRegistrationAuthService.java
  src/main/java/com/netgrif/application/engine/auth/service/interfaces/ILdapUserRefService.java
  src/main/java/com/netgrif/application/engine/configuration/AbstractSecurityConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/ForwardConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/NaeSecurityConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/SecurityConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/SecurityConfigurationStaticEnabled.java
  src/main/java/com/netgrif/application/engine/configuration/authentication/providers/NaeAuthProperties.java
  src/main/java/com/netgrif/application/engine/configuration/authentication/providers/NetgrifAuthenticationProvider.java
  src/main/java/com/netgrif/application/engine/configuration/authentication/providers/basic/NetgrifBasicAuthenticationProvider.java
  src/main/java/com/netgrif/application/engine/configuration/authentication/providers/basic/NetgrifBasicAuthenticationProviderLoader.java
  src/main/java/com/netgrif/application/engine/configuration/authentication/providers/ldap/NetgrifLdapAuthenticationProvider.java
  src/main/java/com/netgrif/application/engine/configuration/authentication/providers/ldap/NetgrifLdapAuthenticationProviderLoader.java
  src/main/java/com/netgrif/application/engine/configuration/authentication/providers/ldap/UserDetailsContextMapperImpl.java
  src/main/java/com/netgrif/application/engine/configuration/properties/NaeLdapProperties.java
  src/main/java/com/netgrif/application/engine/ldap/domain/LdapUserRef.java
  src/main/resources/application.properties
  src/test/groovy/com/netgrif/application/engine/action/AssignActionTest.groovy
  src/test/groovy/com/netgrif/application/engine/auth/FilterAuthorizationServiceTest.groovy
  src/test/groovy/com/netgrif/application/engine/insurance/mvc/InsuranceTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/web/PetriNetControllerTest.groovy
  src/test/java/com/netgrif/application/engine/configuration/authentication/providers/NetgrifLdapAuthenticationProviderTest.java
  src/test/resources/test-server.ldif
Labels: improvement, Extra Large

#53 [NAE-1468] i18n Data field
  docs/data_fields.md
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/I18nField.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/test/groovy/com/netgrif/application/engine/elastic/DataSearchRequestTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/ImporterTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FieldTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/dataset/I18nFieldTest.groovy
  src/test/groovy/com/netgrif/application/engine/workflow/DataServiceTest.groovy
  src/test/groovy/com/netgrif/application/engine/workflow/NewInitTest.groovy
  src/test/resources/all_data.xml
  src/test/resources/data_test.xml
  src/test/resources/initial_behavior.xml
  src/test/resources/petriNets/nae_1276_Init_value_as_choice.xml
Labels: documentation, improvement, new feature, Large

#49 [NAE-1623] Action API consolidation
  docs/services/pdf_generator.md
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FileFieldValue.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfGenerator.java
  src/main/resources/application.properties
  src/main/resources/petriNets/all_data.xml
  src/test/groovy/com/netgrif/application/engine/pdf/service/PdfGeneratorTest.groovy
  src/test/resources/all_data_pdf.xml
  src/test/resources/datagroup_test_layout.xml
  src/test/resources/flow.xml
  src/test/resources/pdf_run_action.xml
  src/test/resources/pdf_test_3.xml
Labels: improvement, Extra Large

#52 [NAE-1622] Change behavior action improvements
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/dataset/ChangeBehaviorTest.groovy
  src/test/resources/change_behavior_update.xml
Labels: improvement, Extra Large
