Repository netgrif/application-engine, pull requests merged in 2022-04, with the labels that each got.

#28 [NAE-1616] - Cannot upload process with action id
  src/main/java/com/netgrif/application/engine/importer/service/Importer.java
  src/test/groovy/com/netgrif/application/engine/action/ActionTest.groovy
  src/test/resources/petriNets/NAE-1616_duplicate_action_id.xml
Labels: bugfix, Large

#29 [NAE-1596] Nets with transitions without titles cannot be read
  src/main/java/com/netgrif/application/engine/importer/service/Importer.java
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/ImporterTest.groovy
  src/test/resources/importTest/NoLabel.xml
Labels: Small

#36 [NAE-1599] Task-reffed fields are not placed in correct position
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/test/groovy/com/netgrif/application/engine/pdf/service/PdfGeneratorTest.groovy
  src/test/groovy/com/netgrif/application/engine/workflow/DataServiceTest.groovy
  src/test/resources/agreement.xml
  src/test/resources/datagroup_test_layout.xml
  src/test/resources/simple_taskref.xml
Labels: bugfix, Large

#37 [NAE-1620] Change workflowService findAllById method
  src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
  src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
Labels: breaking change, Extra Small

#41 [NAE-1599] Task-reffed fields are not placed in correct position
  src/main/resources/petriNets/engine-processes/filter.xml
Labels: Extra Small

#44 Release 6.0.4
  .github/workflows/master-build.yml
  CHANGELOG.md
  pom.xml
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
  src/main/java/com/netgrif/application/engine/importer/service/Importer.java
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
  src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
  src/main/resources/petriNets/engine-processes/filter.xml
  src/test/groovy/com/netgrif/application/engine/action/ActionTest.groovy
  src/test/groovy/com/netgrif/application/engine/importer/ImporterTestGroovy.groovy
  src/test/groovy/com/netgrif/application/engine/pdf/service/PdfGeneratorTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/ImporterTest.groovy
  src/test/groovy/com/netgrif/application/engine/workflow/DataServiceTest.groovy
  src/test/resources/agreement.xml
  src/test/resources/datagroup_no_id_test.xml
  src/test/resources/datagroup_test_layout.xml
  src/test/resources/importTest/NoLabel.xml
  src/test/resources/petriNets/NAE-1616_duplicate_action_id.xml
  src/test/resources/simple_taskref.xml
Labels: Extra Large

#42 [NAE-1440] setData on button without value
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/test/groovy/com/netgrif/application/engine/workflow/SetDataOnButtonTest.groovy
  src/test/resources/button_set_data_test.xml
Labels: improvement, Large

#50 [NAE-1624] Upgrade Elasticsearch Connector
  .github/workflows/master-build.yml
  .github/workflows/pr-build.yml
  .github/workflows/release-build.yml
  THIRD-PARTY.txt
  docker-compose.yml
  pom.xml
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/ButtonField.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/groovy/com/netgrif/application/engine/startup/ElasticsearchRunner.groovy
  src/main/java/com/netgrif/application/engine/elastic/domain/ButtonField.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseMappingService.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticIndexService.java
  src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticIndexService.java
  src/main/java/com/netgrif/application/engine/importer/service/FieldFactory.java
  src/test/groovy/com/netgrif/application/engine/auth/TaskAuthorizationServiceTest.groovy
  src/test/groovy/com/netgrif/application/engine/auth/WorkflowAuthorizationServiceTest.groovy
  src/test/groovy/com/netgrif/application/engine/elastic/DataSearchRequestTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/roles/ProcessRoleTest.groovy
Labels: improvement, Large
