Repository netgrif/application-engine, pull requests merged in 2022-07, with the labels that each got.

#81 [NAE-1666] PDF Generator template file issue
  src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfGenerator.java
Labels: bugfix, Extra Small

#82 [NAE-1665] Generated PDF colors properties
  src/main/java/com/netgrif/application/engine/pdf/generator/config/PdfProperties.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfDrawer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/interfaces/IPdfDrawer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/BooleanFieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/DataGroupFieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/EnumerationRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/FieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/MultiChoiceRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/PageNumberRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/Renderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/SelectionFieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/TextFieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/TitleRenderer.java
  src/main/resources/application.properties
  src/main/resources/pdfGenerator/fonts/Roboto-Bold.ttf
Labels: improvement, Medium

#79 [NAE-1647] Elastic mapping for I18N data field
  src/main/java/com/netgrif/application/engine/elastic/domain/I18nField.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseMappingService.java
Labels: improvement, Extra Small

#78 [NAE-1659] Process URI
  docs/process/uri.md
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/groovy/com/netgrif/application/engine/startup/DefaultFiltersRunner.groovy
  src/main/groovy/com/netgrif/application/engine/startup/DemoRunner.groovy
  src/main/groovy/com/netgrif/application/engine/startup/ElasticsearchRunner.groovy
  src/main/groovy/com/netgrif/application/engine/startup/FilterRunner.groovy
  src/main/groovy/com/netgrif/application/engine/startup/FinisherRunner.groovy
  src/main/groovy/com/netgrif/application/engine/startup/RunnerController.groovy
  src/main/groovy/com/netgrif/application/engine/startup/UriRunner.groovy
  src/main/java/com/netgrif/application/engine/configuration/ElasticsearchConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/properties/UriProperties.java
  src/main/java/com/netgrif/application/engine/elastic/domain/ElasticCase.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
  src/main/java/com/netgrif/application/engine/elastic/web/requestbodies/CaseSearchRequest.java
  src/main/java/com/netgrif/application/engine/orgstructure/groups/NextGroupService.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/PetriNet.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/UriContentType.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/UriNode.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/repositories/PetriNetRepository.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/repository/UriNodeRepository.java
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/UriService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IPetriNetService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IUriService.java
  src/main/java/com/netgrif/application/engine/petrinet/web/PetriNetController.java
  src/main/java/com/netgrif/application/engine/petrinet/web/UriController.java
  src/main/java/com/netgrif/application/engine/petrinet/web/responsebodies/UriNodeResource.java
  src/main/java/com/netgrif/application/engine/petrinet/web/responsebodies/UriNodeResources.java
  src/main/java/com/netgrif/application/engine/workflow/domain/Case.java
  src/main/java/com/netgrif/application/engine/workflow/domain/repositories/CaseRepository.java
  src/main/java/com/netgrif/application/engine/workflow/service/FilterImportExportService.java
  src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IWorkflowService.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/petriNets/FM_v0_2.xml
  src/main/resources/petriNets/all_data.xml
  src/main/resources/petriNets/datamap.xml
  src/main/resources/petriNets/engine-processes/org_group.xml
  src/main/resources/petriNets/engine-processes/preference_filter_item.xml
  src/main/resources/petriNets/insurance_portal_demo.xml
  src/main/resources/petriNets/leukemia.xml
  src/main/resources/petriNets/leukemia_en.xml
  src/main/resources/petriNets/posudky.xml
  src/test/groovy/com/netgrif/application/engine/TestHelper.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/service/UriServiceTest.groovy
Labels: improvement, Extra Large

#83 [NAE-1660] Filter action API
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/groovy/com/netgrif/application/engine/startup/DefaultFiltersRunner.groovy
  src/main/groovy/com/netgrif/application/engine/startup/DemoRunner.groovy
  src/main/java/com/netgrif/application/engine/auth/service/UserService.java
  src/main/java/com/netgrif/application/engine/configuration/ElasticsearchConfiguration.java
  src/main/java/com/netgrif/application/engine/orgstructure/groups/NextGroupService.java
  src/main/java/com/netgrif/application/engine/orgstructure/groups/interfaces/INextGroupService.java
  src/main/java/com/netgrif/application/engine/petrinet/web/UriController.java
  src/main/java/com/netgrif/application/engine/petrinet/web/responsebodies/UriNodeResources.java
  src/main/resources/petriNets/engine-processes/org_group.xml
  src/main/resources/petriNets/engine-processes/preference_filter_item.xml
  src/test/groovy/com/netgrif/application/engine/action/FilterApiTest.groovy
  src/test/groovy/com/netgrif/application/engine/event/GroovyShellFactoryTest.groovy
  src/test/groovy/com/netgrif/application/engine/export/service/ExportServiceTest.groovy
  src/test/resources/petriNets/filter_api_test.xml
  src/test/resources/petriNets/filter_api_test_0.xml
Labels: improvement, breaking change, Extra Large
