Repository netgrif/application-engine, pull requests merged in 2022-11, with the labels that each got.

#142 [NAE-1777] JWT Token user detail not show password
  src/main/java/com/netgrif/application/engine/auth/domain/LoggedUser.java
  src/main/java/com/netgrif/application/engine/configuration/security/PublicAuthenticationFilter.java
  src/main/java/com/netgrif/application/engine/configuration/security/jwt/JwtService.java
Labels: bugfix, Extra Small

#141 [NAE-1773] Action that sets null value to field does not trigger next actions
  src/main/java/com/netgrif/application/engine/workflow/service/EventService.java
  src/test/resources/insurance_portal_demo_test.xml
Labels: bugfix, Extra Small

#135 [NAE-1755] PetriNetService cache no caching "null"
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  src/test/groovy/com/netgrif/application/engine/petrinet/service/CachePetriNetServiceTest.groovy
Labels: Extra Small

#145 [NAE-1780] Configurable CORS security settings
  src/main/java/com/netgrif/application/engine/configuration/AbstractSecurityConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/NaeSecurityConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/properties/SecurityConfigProperties.java
Labels: Extra Small

#131 [NAE-1753] Currency code in PDF
  src/main/java/com/netgrif/application/engine/pdf/generator/service/fieldbuilder/TextFieldBuilder.java
Labels: improvement, Extra Small

#137 [NAE-1756] Delete PetriNet does not call case delete events
  src/main/groovy/com/netgrif/application/engine/AsyncRunner.groovy
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
  src/main/java/com/netgrif/application/engine/elastic/web/requestbodies/CaseSearchRequest.java
  src/main/java/com/netgrif/application/engine/petrinet/web/PetriNetController.java
  src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IWorkflowService.java
  src/test/groovy/com/netgrif/application/engine/action/FilterApiTest.groovy
Labels: bugfix, Extra Small

#143 [NAE-1776] UncaughtExceptionHandler
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticTaskService.java
  src/main/java/com/netgrif/application/engine/elastic/service/executors/Executor.java
Labels: improvement, Extra Small
