Repository netgrif/application-engine, pull requests merged in 2022-08, with the labels that each got.

#87 [NAE-1677] Message from exception thrown in SET event on data field is not propagated in EventOutcome
  src/main/java/com/netgrif/application/engine/workflow/web/AbstractTaskController.java
  src/main/java/com/netgrif/application/engine/workflow/web/PublicTaskController.java
  src/main/java/com/netgrif/application/engine/workflow/web/TaskController.java
  src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/LocalisedTaskResource.java
Labels: bugfix, Extra Small

#96 [NAE-1702] LdapUser unique dn
  src/main/java/com/netgrif/application/engine/ldap/domain/LdapUser.java
Labels: Extra Small

#91 [NAE-1663] Optional constructor
  docker-compose.yml
  src/main/groovy/com/netgrif/application/engine/startup/FilterRunner.groovy
  src/main/groovy/com/netgrif/application/engine/startup/GroupRunner.groovy
  src/main/groovy/com/netgrif/application/engine/startup/ImportHelper.groovy
Labels: Extra Small

#93 [NAE-1699] Create/upload event action is loaded only from the cache
  src/main/java/com/netgrif/application/engine/importer/service/Importer.java
Labels: bugfix, Extra Small

#95 [NAE-1677] Message from exception thrown in SET event on data field is not propagated in EventOutcome
  src/main/java/com/netgrif/application/engine/workflow/web/AbstractTaskController.java
  src/main/java/com/netgrif/application/engine/workflow/web/PublicTaskController.java
  src/main/java/com/netgrif/application/engine/workflow/web/TaskController.java
Labels: Extra Small

#89 [NAE-1691] Default value number field after the change behavior
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/NumberField.groovy
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
Labels: bugfix, Extra Small

#70 [NAE-1646] Overridable data field render in PDF generator
  src/main/java/com/netgrif/application/engine/configuration/PrototypesConfiguration.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfDataHelper.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfDrawer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/PdfGenerator.java
Labels: improvement, Extra Small
