Repository netgrif/application-engine, pull requests merged in 2022-10, with the labels that each got.

#118 [NAE-1728] Simplify value for changing user list
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
Labels: improvement, Extra Small

#119 [NAE-1730] PetriNetService cache fix upload bug
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
Labels: bugfix, Extra Small

#122 [NAE-1733] Organization group process has deprecated attributes and change import system user
  src/main/groovy/com/netgrif/application/engine/startup/ImportHelper.groovy
  src/main/resources/petriNets/engine-processes/org_group.xml
Labels: Extra Small

#125 Release/6.2.3
  CHANGELOG.md
  pom.xml
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/groovy/com/netgrif/application/engine/startup/ImportHelper.groovy
  src/main/java/com/netgrif/application/engine/importer/service/ComponentFactory.java
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  src/main/resources/petriNets/engine-processes/org_group.xml
Labels: Small, release

#128 [NAE-1747] PDF Generator: incorrect file name shortening
  src/main/java/com/netgrif/application/engine/pdf/generator/service/fieldbuilder/TextFieldBuilder.java
Labels: bugfix, Extra Small

#127 [NAE-1748] Incorrect handling for long lines in PDF generator
  src/main/java/com/netgrif/application/engine/pdf/generator/service/fieldbuilder/FieldBuilder.java
Labels: bugfix, Extra Small

#130 Release/6.2.4
  CHANGELOG.md
  pom.xml
  src/main/java/com/netgrif/application/engine/pdf/generator/service/fieldbuilder/FieldBuilder.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/fieldbuilder/TextFieldBuilder.java
Labels: Extra Small, release

#133 [NAE-1761] LoggedUser circular dependency
  src/main/java/com/netgrif/application/engine/auth/domain/LoggedUser.java
Labels: bugfix, Extra Small

#134 [NAE-1762] Public view URL encoding
  src/main/java/com/netgrif/application/engine/petrinet/web/PublicPetriNetController.java
Labels: improvement, Extra Small
