Repository netgrif/application-engine, pull requests merged in 2022-06, with the labels that each got.

#73 [NAE-1652] For some PDF documents the file preview is not generating
  pom.xml
Labels: bugfix, Extra Small

#74 [NAE-1641] Generate PDF with special characters
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/FieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/Renderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/SelectionFieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/TextFieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/TitleRenderer.java
Labels: bugfix, Extra Small

#76 Release 6.1.1
  CHANGELOG.md
  pom.xml
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/java/com/netgrif/application/engine/auth/service/LdapUserDetailsService.java
  src/main/java/com/netgrif/application/engine/auth/service/interfaces/ILdapUserRefService.java
  src/main/java/com/netgrif/application/engine/configuration/LdapUserServiceConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/authentication/providers/ldap/NetgrifLdapAuthenticationProvider.java
  src/main/java/com/netgrif/application/engine/configuration/authentication/providers/ldap/NetgrifLdapAuthenticationProviderLoader.java
  src/main/java/com/netgrif/application/engine/configuration/authentication/providers/ldap/UserDetailsContextMapperImpl.java
  src/main/java/com/netgrif/application/engine/configuration/ldap/AdLdapConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/ldap/LdapConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/properties/NaeLdapProperties.java
  src/main/java/com/netgrif/application/engine/ldap/domain/LdapGroup.java
  src/main/java/com/netgrif/application/engine/ldap/domain/LdapGroupRef.java
  src/main/java/com/netgrif/application/engine/ldap/domain/LdapLoggedUser.java
  src/main/java/com/netgrif/application/engine/ldap/domain/LdapUser.java
  src/main/java/com/netgrif/application/engine/ldap/domain/LdapUserRef.java
  src/main/java/com/netgrif/application/engine/ldap/domain/repository/LdapGroupRoleRepository.java
  src/main/java/com/netgrif/application/engine/ldap/domain/repository/LdapUserRefRepository.java
  src/main/java/com/netgrif/application/engine/ldap/domain/repository/LdapUserRepository.java
  src/main/java/com/netgrif/application/engine/ldap/service/LdapGroupRefService.java
  src/main/java/com/netgrif/application/engine/ldap/service/LdapUserRefService.java
  src/main/java/com/netgrif/application/engine/ldap/service/LdapUserService.java
  src/main/java/com/netgrif/application/engine/ldap/service/interfaces/ILdapGroupRefService.java
  src/main/java/com/netgrif/application/engine/orgstructure/web/LdapController.java
  src/main/java/com/netgrif/application/engine/orgstructure/web/responsebodies/LdapGroupResponseBody.java
  src/main/java/com/netgrif/application/engine/orgstructure/web/responsebodies/LdapGroupsResource.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/FieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/Renderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/SelectionFieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/TextFieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/TitleRenderer.java
  src/main/java/com/netgrif/application/engine/workflow/web/PublicAbstractController.java
Labels: Medium

#77 Release 6.1.1
  .gitignore
  CHANGELOG.md
  README.md
  pom.xml
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/java/com/netgrif/application/engine/auth/service/LdapUserDetailsService.java
  src/main/java/com/netgrif/application/engine/auth/service/interfaces/ILdapUserRefService.java
  src/main/java/com/netgrif/application/engine/configuration/LdapUserServiceConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/authentication/providers/ldap/NetgrifLdapAuthenticationProvider.java
  src/main/java/com/netgrif/application/engine/configuration/authentication/providers/ldap/NetgrifLdapAuthenticationProviderLoader.java
  src/main/java/com/netgrif/application/engine/configuration/authentication/providers/ldap/UserDetailsContextMapperImpl.java
  src/main/java/com/netgrif/application/engine/configuration/ldap/AdLdapConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/ldap/LdapConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/properties/NaeLdapProperties.java
  src/main/java/com/netgrif/application/engine/ldap/domain/LdapGroup.java
  src/main/java/com/netgrif/application/engine/ldap/domain/LdapGroupRef.java
  src/main/java/com/netgrif/application/engine/ldap/domain/LdapLoggedUser.java
  src/main/java/com/netgrif/application/engine/ldap/domain/LdapUser.java
  src/main/java/com/netgrif/application/engine/ldap/domain/LdapUserRef.java
  src/main/java/com/netgrif/application/engine/ldap/domain/repository/LdapGroupRoleRepository.java
  src/main/java/com/netgrif/application/engine/ldap/domain/repository/LdapUserRefRepository.java
  src/main/java/com/netgrif/application/engine/ldap/domain/repository/LdapUserRepository.java
  src/main/java/com/netgrif/application/engine/ldap/service/LdapGroupRefService.java
  src/main/java/com/netgrif/application/engine/ldap/service/LdapUserRefService.java
  src/main/java/com/netgrif/application/engine/ldap/service/LdapUserService.java
  src/main/java/com/netgrif/application/engine/ldap/service/interfaces/ILdapGroupRefService.java
  src/main/java/com/netgrif/application/engine/orgstructure/web/LdapController.java
  src/main/java/com/netgrif/application/engine/orgstructure/web/responsebodies/LdapGroupResponseBody.java
  src/main/java/com/netgrif/application/engine/orgstructure/web/responsebodies/LdapGroupsResource.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/FieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/Renderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/SelectionFieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/TextFieldRenderer.java
  src/main/java/com/netgrif/application/engine/pdf/generator/service/renderer/TitleRenderer.java
  src/main/java/com/netgrif/application/engine/workflow/web/PublicAbstractController.java
Labels: Medium, release
