Repository netgrif/application-engine, pull requests merged in 2022-02, with the labels that each got.

#1 GitHub workflow
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr-build.yml
  pom.xml
Labels: Extra Small

#2 Test workflow
  .github/workflows/master-build.yml
  .github/workflows/pr-build.yml
  .github/workflows/release-build.yml
  docker-compose.yml
  src/test/groovy/com/netgrif/application/engine/menu/MenuImportExportTest.groovy
Labels: Large

#4 Nae 1572 - FilterImportExportService service does not assign import_filter tasks
  src/main/java/com/netgrif/application/engine/workflow/service/FilterImportExportService.java
  src/main/java/com/netgrif/application/engine/workflow/service/MenuImportExportService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IFilterImportExportService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IMenuImportExportService.java
Labels: Extra Small

#5 Nae 1573 - GET event is initialized with SET type
  pom.xml
  src/main/java/com/netgrif/application/engine/importer/service/Importer.java
Labels: Extra Small

#7 [NAE-1557] Cannot clear optional enumeration
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
Labels: bugfix, Extra Small

#8 [NAE-1559] Keyword 'this' in event actions
  src/main/java/com/netgrif/application/engine/importer/service/Importer.java
  src/test/groovy/com/netgrif/application/engine/importer/ImporterTestGroovy.groovy
  src/test/resources/this_kw_test.xml
Labels: bugfix, Medium

#9 [NAE-1578] Make createSetDataEventOutcome protected
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
Labels: bugfix, new feature, Extra Small

#11 [NAE-1581] Public view create case permission check
  src/main/java/com/netgrif/application/engine/workflow/web/PublicWorkflowController.java
Labels: bugfix, Extra Small

#12 [NAE-1582] Group is not added into User.nextGroups when invited
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
Labels: bugfix, Extra Small
