Repository netgrif/application-engine, pull requests merged in 2023-12, with the labels that each got.

#232 [NAE-1930] Modify Annotation in LdapUser Class for Indexing
  src/main/java/com/netgrif/application/engine/ldap/domain/LdapUser.java
Labels: bugfix, Extra Small

#233 [NAE-1932] Enhancement of Redis Connector to Support Authentication
  src/main/java/com/netgrif/application/engine/configuration/SessionConfiguration.java
Labels: Extra Small

#230 [NAE-1929] Data field type list of strings
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FieldType.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/StringCollectionField.groovy
  src/main/java/com/netgrif/application/engine/importer/service/FieldFactory.java
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
Labels: improvement, new feature, Extra Small

#234 [NAE-1934] Remove devtools dependency
  pom.xml
Labels: Extra Small

#231 [NAE-1931] Implementation of Index Re-Creation after MongoDB Database Drop
  src/main/groovy/com/netgrif/application/engine/startup/MongoDbRunner.groovy
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticTaskService.java
  src/main/java/com/netgrif/application/engine/elastic/service/executors/ExecutorMaxSizeHashMap.java
  src/main/resources/application.properties
Labels: bugfix, Small
