Repository netgrif/application-engine, pull requests merged in 2023-05, with the labels that each got.

#194 [NAE-1875] Namespace functions cause memory leak
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/FieldActionsRunner.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/FunctionsTest.groovy
  src/test/resources/petriNets/function_res_v2.xml
  src/test/resources/petriNets/function_test_v2.xml
Labels: bugfix, Extra Small

#190 [NAE-1868] Process role refresh
  .github/workflows/pr-build.yml
  src/main/java/com/netgrif/application/engine/configuration/security/SecurityContextFilter.java
  src/main/java/com/netgrif/application/engine/security/service/ISecurityContextService.java
  src/main/java/com/netgrif/application/engine/security/service/SecurityContextService.java
  src/main/java/com/netgrif/application/engine/workflow/service/AbstractAuthorizationService.java
  src/test/groovy/com/netgrif/application/engine/auth/SecurityContextTest.groovy
  src/test/java/com/netgrif/application/engine/petrinet/service/ProcessRoleServiceTest.java
  src/test/java/com/netgrif/application/engine/workflow/service/AbstractAuthorizationServiceTest.java
  src/test/resources/all_data.xml
Labels: bugfix, Small

#193 [NAE-1874] Filtering users based on roles when selecting users for UserListField
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/UserListField.groovy
  src/main/java/com/netgrif/application/engine/importer/service/FieldFactory.java
  src/main/java/com/netgrif/application/engine/workflow/domain/Case.java
  src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/LocalisedFieldFactory.java
  src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/LocalisedUserListField.java
Labels: improvement

#120 [NAE-1678] User impersonation
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/java/com/netgrif/application/engine/auth/service/UserService.java
  src/main/java/com/netgrif/application/engine/configuration/NaeSecurityConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/SessionConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/security/AuthenticationService.java
  src/main/java/com/netgrif/application/engine/configuration/security/ImpersonationRequestFilter.java
  src/main/java/com/netgrif/application/engine/history/domain/baseevent/EventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/baseevent/repository/EventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/caseevents/CaseEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/caseevents/CreateCaseEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/caseevents/DeleteCaseEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/caseevents/repository/CreateCaseEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/caseevents/repository/DeleteCaseEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/dataevents/GetDataEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/dataevents/SetDataEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/dataevents/repository/GetDataEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/dataevents/repository/SetDataEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/impersonationevents/ImpersonationEndEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/impersonationevents/ImpersonationEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/impersonationevents/ImpersonationStartEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/petrinetevents/DeletePetriNetEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/petrinetevents/ImportPetriNetEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/petrinetevents/PetriNetEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/petrinetevents/repository/DeletePetriNetEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/petrinetevents/repository/ImportPetriNetEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/taskevents/AssignTaskEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/taskevents/CancelTaskEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/taskevents/DelegateTaskEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/taskevents/FinishTaskEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/taskevents/TaskEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/taskevents/repository/AssignTaskEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/taskevents/repository/CancelTaskEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/taskevents/repository/DelegateTaskEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/taskevents/repository/FinishTaskEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/userevents/AdminActionEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/userevents/IProcessRolesEvent.java
  src/main/java/com/netgrif/application/engine/history/domain/userevents/UserEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/userevents/UserRoleEventLog.java
  src/main/java/com/netgrif/application/engine/history/service/HistoryService.java
  src/main/java/com/netgrif/application/engine/history/service/IHistoryService.java
  src/main/java/com/netgrif/application/engine/history/service/listener/UserEventListener.java
  src/main/java/com/netgrif/application/engine/impersonation/service/ImpersonationService.java
  src/main/java/com/netgrif/application/engine/impersonation/service/interfaces/IImpersonationService.java
  src/main/java/com/netgrif/application/engine/importer/service/Importer.java
  src/main/java/com/netgrif/application/engine/ldap/domain/LdapLoggedUser.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Place.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/Arc.java
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IPetriNetService.java
  src/main/java/com/netgrif/application/engine/petrinet/web/PetriNetController.java
  src/main/java/com/netgrif/application/engine/petrinet/web/responsebodies/ArcImportReference.java
  src/main/java/com/netgrif/application/engine/petrinet/web/responsebodies/PetriNetImportReference.java
  src/main/java/com/netgrif/application/engine/petrinet/web/responsebodies/PlaceImportReference.java
  src/main/java/com/netgrif/application/engine/petrinet/web/responsebodies/TransitionImportReference.java
  src/main/resources/petriNets/engine-processes/impersonation_config.xml
  src/test/groovy/com/netgrif/application/engine/history/HistoryServiceTest.groovy
Labels: bugfix, Extra Large

#198 Release/6.2.9
  CHANGELOG.md
  pom.xml
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/java/com/netgrif/application/engine/history/service/HistoryService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IPetriNetService.java
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
  src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IDataService.java
  src/test/groovy/com/netgrif/application/engine/auth/TaskAuthorizationServiceTest.groovy
  src/test/groovy/com/netgrif/application/engine/auth/WorkflowAuthorizationServiceTest.groovy
  src/test/groovy/com/netgrif/application/engine/permissions/ElasticSearchViewPermissionTest.groovy
  src/test/groovy/com/netgrif/application/engine/permissions/QueryDSLViewPermissionTest.groovy
  src/test/groovy/com/netgrif/application/engine/workflow/UserRefsTest.groovy
Labels: Large

#163 [NAE-1722] Set default view headers with the CreateMenuItem action method
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/resources/petriNets/engine-processes/preference_filter_item.xml
  src/test/groovy/com/netgrif/application/engine/action/FilterApiTest.groovy
Labels: improvement, Medium

#117 [NAE-1703] Dashboard
  src/main/resources/petriNets/dashboard.xml
  src/main/resources/petriNets/dashboard_tile.xml
Labels: new feature, Extra Large

#195 [NAE-1865] - Grid rendering performance improvement
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/groovy/com/netgrif/application/engine/startup/ImportHelper.groovy
  src/main/java/com/netgrif/application/engine/history/service/HistoryService.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/PetriNet.java
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  src/main/java/com/netgrif/application/engine/rules/service/RuleEngine.java
  src/main/java/com/netgrif/application/engine/rules/service/interfaces/IRuleEngine.java
  src/main/java/com/netgrif/application/engine/workflow/service/EventService.java
  src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
  src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/ITaskService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IWorkflowService.java
  src/test/groovy/com/netgrif/application/engine/history/HistoryServiceTest.groovy
  src/test/groovy/com/netgrif/application/engine/validation/ValidationTest.groovy
  src/test/java/com/netgrif/application/engine/workflow/service/TaskServiceTest.java
Labels: Large

#108 [NAE-1723] EventLog classes are not resolved correctly after search in MongoDB collection
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/java/com/netgrif/application/engine/elastic/web/requestbodies/CaseSearchRequest.java
  src/main/java/com/netgrif/application/engine/history/domain/caseevents/repository/CreateCaseEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/caseevents/repository/DeleteCaseEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/dataevents/repository/GetDataEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/dataevents/repository/SetDataEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/petrinetevents/repository/DeletePetriNetEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/petrinetevents/repository/ImportPetriNetEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/taskevents/AssignTaskEventLog.java
  src/main/java/com/netgrif/application/engine/history/domain/taskevents/repository/AssignTaskEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/taskevents/repository/CancelTaskEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/taskevents/repository/DelegateTaskEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/domain/taskevents/repository/FinishTaskEventLogRepository.java
  src/main/java/com/netgrif/application/engine/history/service/HistoryService.java
  src/main/resources/application-dev.properties
Labels: bugfix, Extra Small

#201 [NAE-1836] Actions cache is broken (for multiple versions of the same process)
  src/main/java/com/netgrif/application/engine/workflow/service/FieldActionsCacheService.java
Labels: Extra Small

#187 [NAE-1864] Deleting process version removes instances of all versions of the same process
  src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
Labels: Extra Small

#191 [NAE-1870] Indeterministic order in multichoice and multichoice map v…
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/MultichoiceField.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/MultichoiceMapField.groovy
  src/main/java/com/netgrif/application/engine/importer/service/FieldFactory.java
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/LocalisedMultichoiceMapField.java
Labels: bugfix, Extra Small

#160 [NAE-1807] Reference in Arc is not cloned properly
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/Action.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/runner/Expression.groovy
  src/main/java/com/netgrif/application/engine/auth/domain/Author.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Component.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/DataFieldLogic.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/I18nString.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Icon.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/PetriNet.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Position.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Transaction.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Transition.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/Arc.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/InhibitorArc.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/ReadArc.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/reference/Referencable.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/reference/Reference.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/events/CaseEvent.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/events/DataEvent.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/events/Event.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/events/ProcessEvent.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/layout/TaskLayout.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/roles/ProcessRole.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/version/Version.java
  src/main/java/com/netgrif/application/engine/workflow/domain/DataField.java
Labels: Medium
