Repository netgrif/application-engine, pull requests merged in 2023-07, with the labels that each got.

#215 Release/6.3.1
  CHANGELOG.md
  pom.xml
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/MultichoiceField.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/MultichoiceMapField.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/Action.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/runner/Expression.groovy
  src/main/java/com/netgrif/application/engine/auth/domain/Author.java
  src/main/java/com/netgrif/application/engine/auth/service/RegistrationService.java
  src/main/java/com/netgrif/application/engine/configuration/PublicViewProperties.java
  src/main/java/com/netgrif/application/engine/importer/service/FieldFactory.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Component.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/DataFieldLogic.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/I18nString.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Icon.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/PetriNet.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Position.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Transaction.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Transition.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/Arc.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/InhibitorArc.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/ReadArc.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/reference/Referencable.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/reference/Reference.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/events/CaseEvent.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/events/DataEvent.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/events/Event.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/events/ProcessEvent.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/layout/TaskLayout.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/roles/ProcessRole.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/version/Version.java
  src/main/java/com/netgrif/application/engine/workflow/domain/DataField.java
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/main/java/com/netgrif/application/engine/workflow/service/FieldActionsCacheService.java
  src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
  src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/LocalisedMultichoiceMapField.java
  src/test/groovy/com/netgrif/application/engine/action/ActionDelegateTest.groovy
  src/test/resources/application-test.properties
Labels: Large

#216 Release 6.3.1
  CHANGELOG.md
  pom.xml
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/MultichoiceField.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/MultichoiceMapField.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/Action.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/runner/Expression.groovy
  src/main/java/com/netgrif/application/engine/auth/domain/Author.java
  src/main/java/com/netgrif/application/engine/auth/service/RegistrationService.java
  src/main/java/com/netgrif/application/engine/configuration/PublicViewProperties.java
  src/main/java/com/netgrif/application/engine/importer/service/FieldFactory.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Component.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/DataFieldLogic.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/I18nString.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Icon.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/PetriNet.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Position.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Transaction.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Transition.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/Arc.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/InhibitorArc.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/ReadArc.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/reference/Referencable.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/arcs/reference/Reference.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/events/CaseEvent.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/events/DataEvent.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/events/Event.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/events/ProcessEvent.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/layout/TaskLayout.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/roles/ProcessRole.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/version/Version.java
  src/main/java/com/netgrif/application/engine/workflow/domain/DataField.java
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/main/java/com/netgrif/application/engine/workflow/service/FieldActionsCacheService.java
  src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
  src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/LocalisedMultichoiceMapField.java
  src/test/groovy/com/netgrif/application/engine/action/ActionDelegateTest.groovy
  src/test/groovy/com/netgrif/application/engine/action/FilterApiTest.groovy
  src/test/resources/application-test.properties
Labels: Large, release

#214 [NAE-1497] Frontend actions
  docs/actions/frontend-actions.md
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/FrontAction.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/Frontend.groovy
  src/main/java/com/netgrif/application/engine/workflow/domain/eventoutcomes/EventOutcome.java
  src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/eventoutcomes/base/LocalisedEventOutcome.java
Labels: improvement, new feature, Large
