Repository netgrif/application-engine, pull requests merged in 2023-03, with the labels that each got.

#168 [NAE-1829] UserFieldValue does not implements .toString() method
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/UserFieldValue.groovy
Labels: bugfix, improvement, Extra Small

#173 [NAE-1840] Configurable timeout for failed login attempts
  docker-compose.yml
  src/main/groovy/com/netgrif/application/engine/startup/ImportHelper.groovy
  src/main/java/com/netgrif/application/engine/auth/service/LoginAttemptService.java
  src/main/java/com/netgrif/application/engine/configuration/NaeSecurityConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/authentication/providers/basic/NetgrifBasicAuthenticationProvider.java
  src/main/java/com/netgrif/application/engine/configuration/authentication/providers/ldap/NetgrifLdapAuthenticationProvider.java
  src/main/java/com/netgrif/application/engine/configuration/properties/SecurityLimitsProperties.java
  src/main/java/com/netgrif/application/engine/configuration/quartz/QuartzConfiguration.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/groovy/com/netgrif/application/engine/auth/LoginAttemptsTest.groovy
  src/test/resources/application-test-ldap.properties
  src/test/resources/application-test.properties
Labels: bugfix, Large

#169 [NAE-1831] Taks with negative permissions displayed
  src/main/java/com/netgrif/application/engine/workflow/service/TaskSearchService.java
Labels: Extra Small

#171 [NAE-1834] ExportService - Export CSV files in given charset
  src/main/java/com/netgrif/application/engine/export/domain/ExportDataConfig.java
  src/main/java/com/netgrif/application/engine/export/service/ExportService.java
  src/main/java/com/netgrif/application/engine/export/service/interfaces/IExportService.java
  src/test/resources/petriNets/NAE-1290_Export_actions.xml
Labels: Extra Small

#176 [NAE-1854] Remove deprecated services
  src/main/groovy/com/netgrif/application/engine/business/orsr/IOrsrService.groovy
  src/main/groovy/com/netgrif/application/engine/business/orsr/OrsrReference.groovy
  src/main/groovy/com/netgrif/application/engine/business/orsr/OrsrService.groovy
  src/main/groovy/com/netgrif/application/engine/business/psc/PostalCodePostRequestService.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/FieldActionsRunner.groovy
  src/main/groovy/com/netgrif/application/engine/startup/PostalCodeImporter.groovy
  src/main/groovy/com/netgrif/application/engine/startup/RunnerController.groovy
  src/main/java/com/netgrif/application/engine/business/IPostalCodeService.java
  src/main/java/com/netgrif/application/engine/business/PostalCode.java
  src/main/java/com/netgrif/application/engine/business/PostalCodeRepository.java
  src/main/java/com/netgrif/application/engine/business/PostalCodeService.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/main/resources/petriNets/insurance_portal_demo.xml
  src/main/resources/petriNets/insurance_role_test.xml
  src/main/resources/petriNets/mortgage/address.xml
  src/main/resources/postal_codes.csv
  src/main/resources/postal_codes_dev.csv
  src/test/groovy/com/netgrif/application/engine/insurance/OrsrTest.groovy
  src/test/resources/application-test-ldap.properties
  src/test/resources/application-test.properties
Labels: Extra Large

#180 [NAE-1860] Assigning authority to a user via REST API ends up with error
  src/main/groovy/com/netgrif/application/engine/startup/DemoRunner.groovy
  src/main/java/com/netgrif/application/engine/auth/domain/Authority.java
  src/main/java/com/netgrif/application/engine/auth/service/AbstractUserService.java
  src/main/java/com/netgrif/application/engine/auth/service/UserService.java
  src/main/java/com/netgrif/application/engine/auth/service/interfaces/IUserService.java
Labels: bugfix, critical, Extra Small

#181 [NAE-1861] Requesting unknown endpoint ends with Stackoverflow
  src/main/java/com/netgrif/application/engine/configuration/ForwardConfiguration.java
  src/test/groovy/com/netgrif/application/engine/event/GroovyShellFactoryTest.groovy
Labels: bugfix, Extra Small
