Repository netgrif/application-engine, pull requests merged in 2023-02, with the labels that each got.

#147 [NAE-1759] Update documentation of public views, PDF generator and user list
  docs/roles/userlist.md
  docs/services/pdf_generator.md
  docs/views/public_view.md
Labels: Large

#162 [NAE-1812] Clicking on a column in the case-view that does not have a value has an error behavior
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
Labels: bugfix, Extra Small

#164 [NAE-1811] Process delete does not delete ldap group roles
  src/main/java/com/netgrif/application/engine/ldap/service/LdapGroupRefService.java
  src/main/java/com/netgrif/application/engine/ldap/service/interfaces/ILdapGroupRefService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
Labels: bugfix, Extra Small

#136 [NAE-1757] Multichoice and enumeration options not working
  src/main/java/com/netgrif/application/engine/importer/service/FieldFactory.java
Labels: improvement, Extra Small

#111 [NAE-1638] Elasticsearch executor shutdown
  docker-compose.yml
  src/main/groovy/com/netgrif/application/engine/startup/SuperCreator.groovy
  src/main/java/com/netgrif/application/engine/configuration/ElasticServiceConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/ElasticsearchConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/properties/ElasticsearchProperties.java
  src/main/java/com/netgrif/application/engine/configuration/properties/ExecutorProperties.java
  src/main/java/com/netgrif/application/engine/elastic/service/ReindexingTask.java
  src/main/java/com/netgrif/application/engine/elastic/service/executors/Executor.java
  src/main/java/com/netgrif/application/engine/elastic/service/executors/ExecutorMaxSizeHashMap.java
  src/main/java/com/netgrif/application/engine/elastic/web/ElasticController.java
  src/main/resources/application.properties
  src/test/groovy/com/netgrif/application/engine/elastic/ReindexTest.groovy
Labels: Medium

#112 [NAE-1630] Add admin endpoint for invalidating user session
  pom.xml
  src/main/java/com/netgrif/application/engine/configuration/NaeSecurityConfiguration.java
  src/main/java/com/netgrif/application/engine/manager/service/SessionManagerService.java
  src/main/java/com/netgrif/application/engine/manager/service/interfaces/ISessionManagerService.java
  src/main/java/com/netgrif/application/engine/manager/service/interfaces/SessionImpl.java
  src/main/java/com/netgrif/application/engine/manager/web/SessionManagerController.java
  src/main/java/com/netgrif/application/engine/manager/web/body/request/LogoutRequest.java
  src/main/java/com/netgrif/application/engine/manager/web/body/response/AllLoggedUsersResponse.java
  src/main/java/com/netgrif/application/engine/manager/web/body/response/MessageLogoutResponse.java
  src/test/java/com/netgrif/application/engine/manager/SessionManagerServiceTest.java
  src/test/java/com/netgrif/application/engine/manager/responseclass/ResponseTest.java
Labels: Large

#167 [NAE-1805] Data fields validations are not run on backend
  .github/workflows/master-build.yml
  .github/workflows/pr-build.yml
  .github/workflows/release-build.yml
  pom.xml
  src/main/groovy/com/netgrif/application/engine/validation/domain/ValidationDataInput.groovy
  src/main/groovy/com/netgrif/application/engine/validation/models/AbstractFieldValidation.groovy
  src/main/groovy/com/netgrif/application/engine/validation/models/BooleanFieldValidation.groovy
  src/main/groovy/com/netgrif/application/engine/validation/models/DateFieldValidation.groovy
  src/main/groovy/com/netgrif/application/engine/validation/models/DateTimeFieldValidation.groovy
  src/main/groovy/com/netgrif/application/engine/validation/models/EnumerationFieldValidation.groovy
  src/main/groovy/com/netgrif/application/engine/validation/models/I18nFieldValidation.groovy
  src/main/groovy/com/netgrif/application/engine/validation/models/NumberFieldValidation.groovy
  src/main/groovy/com/netgrif/application/engine/validation/models/TextFieldValidation.groovy
  src/main/groovy/com/netgrif/application/engine/validation/service/ValidationService.groovy
  src/main/groovy/com/netgrif/application/engine/validation/service/interfaces/IValidationService.groovy
  src/main/java/com/netgrif/application/engine/workflow/domain/DataField.java
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
  src/main/resources/application.properties
  src/main/resources/petriNets/engine-processes/org_group.xml
  src/test/groovy/com/netgrif/application/engine/validation/BooleanFieldValidationTest.groovy
  src/test/groovy/com/netgrif/application/engine/validation/NumberFieldValidationTest.groovy
  src/test/groovy/com/netgrif/application/engine/validation/TextFieldValidationTest.groovy
  src/test/groovy/com/netgrif/application/engine/validation/ValidationTest.groovy
  src/test/resources/petriNets/validation/valid_boolean.xml
  src/test/resources/petriNets/validation/valid_date.xml
  src/test/resources/petriNets/validation/valid_number.xml
  src/test/resources/petriNets/validation/valid_regex.xml
  src/test/resources/petriNets/validation/valid_text.xml
Labels: bugfix, Extra Large

#165 [NAE-1607] Allowed nets configuration for newly created filter
  src/main/resources/petriNets/engine-processes/filter.xml
  src/main/resources/petriNets/engine-processes/org_group.xml
  src/main/resources/petriNets/engine-processes/preference_filter_item.xml
  src/test/groovy/com/netgrif/application/engine/insurance/OrsrTest.groovy
Labels: improvement, Extra Small

#161 [NAE-1804] In UserList field can choose one user multiple times
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/UserFieldValue.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/UserListFieldValue.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
Labels: bugfix, improvement, bug, Extra Small

#170 [NAE-1833] Configuration priority search
  src/main/java/com/netgrif/application/engine/configuration/ElasticCaseSearchConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/ElasticServiceConfiguration.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCasePrioritySearch.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
  src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticCasePrioritySearch.java
  src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticCaseService.java
Labels: Small
