Repository netgrif/application-engine, pull requests merged in 2024-03, with the labels that each got.

#203 [NAE-1884] Improve execution of auto trigger tasks
  src/main/java/com/netgrif/application/engine/importer/service/FieldFactory.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/PetriNet.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Transition.java
  src/main/java/com/netgrif/application/engine/workflow/domain/TaskNotFoundException.java
  src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/ITaskService.java
Labels: Small

#166 [NAE-1813] Field id as path variable in TaskController
  src/main/java/com/netgrif/application/engine/workflow/web/AbstractTaskController.java
  src/main/java/com/netgrif/application/engine/workflow/web/PublicTaskController.java
  src/main/java/com/netgrif/application/engine/workflow/web/TaskController.java
  src/main/java/com/netgrif/application/engine/workflow/web/WorkflowController.java
  src/main/java/com/netgrif/application/engine/workflow/web/requestbodies/file/FileFieldRequest.java
  src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/LocalisedTaskResource.java
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FileFieldTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FileListFieldTest.groovy
Labels: bugfix, Medium

#251 [NAE-1956] setData fails on setting allowedNets without value key
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
Labels: Extra Small

#252 [NAE-1955] Update setData to handle options / choices
  src/main/java/com/netgrif/application/engine/petrinet/domain/I18nStringDeserializer.java
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/test/groovy/com/netgrif/application/engine/workflow/DataServiceTest.groovy
Labels: Medium
