Repository netgrif/application-engine, pull requests merged in 2024-01, with the labels that each got.

#237 [NAE-1938] Slow Indexing of Elastic Tasks
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/Action.groovy
  src/main/java/com/netgrif/application/engine/configuration/ElasticServiceConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/ElasticTaskExecutorConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/properties/ElasticTaskExecutorProperties.java
  src/main/java/com/netgrif/application/engine/elastic/domain/ElasticJob.java
  src/main/java/com/netgrif/application/engine/elastic/domain/ElasticTaskJob.java
  src/main/java/com/netgrif/application/engine/elastic/domain/ElasticTaskRepository.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticTaskQueueManager.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticTaskService.java
  src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticTaskService.java
  src/main/java/com/netgrif/application/engine/petrinet/web/PetriNetController.java
  src/test/groovy/com/netgrif/application/engine/elastic/ElasticTaskTest.groovy
  src/test/groovy/com/netgrif/application/engine/elastic/ReindexTest.groovy
Labels: bugfix, Large

#239 Release 6.3.3
  .github/workflows/master-build.yml
  .github/workflows/pr-build.yml
  .github/workflows/release-build.yml
  CHANGELOG.md
  pom.xml
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/Action.groovy
  src/main/groovy/com/netgrif/application/engine/startup/MongoDbRunner.groovy
  src/main/java/com/netgrif/application/engine/configuration/ElasticServiceConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/ElasticTaskExecutorConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/SessionConfiguration.java
  src/main/java/com/netgrif/application/engine/configuration/properties/ElasticTaskExecutorProperties.java
  src/main/java/com/netgrif/application/engine/elastic/domain/ElasticJob.java
  src/main/java/com/netgrif/application/engine/elastic/domain/ElasticTaskJob.java
  src/main/java/com/netgrif/application/engine/elastic/domain/ElasticTaskRepository.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticTaskQueueManager.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticTaskService.java
  src/main/java/com/netgrif/application/engine/elastic/service/executors/ExecutorMaxSizeHashMap.java
  src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticTaskService.java
  src/main/java/com/netgrif/application/engine/ldap/domain/LdapUser.java
  src/main/java/com/netgrif/application/engine/petrinet/web/PetriNetController.java
  src/main/resources/application.properties
  src/test/groovy/com/netgrif/application/engine/elastic/ElasticTaskTest.groovy
  src/test/groovy/com/netgrif/application/engine/elastic/ReindexTest.groovy
Labels: Extra Large

#236 [NAE-1937] Fix the problem with empty string in filter
  src/main/java/com/netgrif/application/engine/workflow/service/CaseSearchService.java
Labels: Extra Small

#235 [NAE-1936] Disable create case button using menu items
  src/main/java/com/netgrif/application/engine/workflow/domain/menu/MenuItemBody.java
  src/main/java/com/netgrif/application/engine/workflow/domain/menu/MenuItemConstants.java
  src/main/resources/petriNets/engine-processes/preference_item.xml
Labels: Extra Small
