Repository netgrif/application-engine, pull requests merged in 2024-09, with the labels that each got.

#259 [NAE-1979] Optimize Maven Resources Plugin Configuration for Correct File Filtering and Copying
  pom.xml
Labels: update

#243 [NAE-1946] Remote file connector to S3
  .github/workflows/master-build.yml
  .github/workflows/pr-build.yml
  .github/workflows/release-build.yml
  docker-compose.yml
  pom.xml
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FileField.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FileFieldDataType.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FileFieldValue.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FileListField.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FileListFieldValue.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/MinIoStorage.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/Storage.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/StorageField.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/StorageType.groovy
  src/main/java/com/netgrif/application/engine/files/StorageResolverService.java
  src/main/java/com/netgrif/application/engine/files/interfaces/IStorageService.java
  src/main/java/com/netgrif/application/engine/files/local/LocalStorageService.java
  src/main/java/com/netgrif/application/engine/files/minio/MinIoHostInfo.java
  src/main/java/com/netgrif/application/engine/files/minio/MinIoProperties.java
  src/main/java/com/netgrif/application/engine/files/minio/MinIoStorageService.java
  src/main/java/com/netgrif/application/engine/files/throwable/BadRequestException.java
  src/main/java/com/netgrif/application/engine/files/throwable/ServiceErrorException.java
  src/main/java/com/netgrif/application/engine/files/throwable/StorageException.java
  src/main/java/com/netgrif/application/engine/files/throwable/StorageNotEnabledException.java
  src/main/java/com/netgrif/application/engine/files/throwable/StorageNotFoundException.java
  src/main/java/com/netgrif/application/engine/importer/service/FieldFactory.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/dataset/factory/StorageFactory.java
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/main/java/com/netgrif/application/engine/workflow/service/MenuImportExportService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IDataService.java
  src/main/java/com/netgrif/application/engine/workflow/web/requestbodies/file/FileFieldRequest.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FileFieldTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FileListFieldTest.groovy
  src/test/groovy/com/netgrif/application/engine/workflow/NewInitTest.groovy
  src/test/resources/application-test.properties
  src/test/resources/petriNets/nae_1276_Init_value_as_choice.xml
  src/test/resources/remoteFileField.xml
  src/test/resources/remoteFileListField.xml
Labels: Extra Large

#246 [NAE-1945] External resource loader
  docs/resources/resources_loading.md
  src/main/java/com/netgrif/application/engine/resource/domain/ExternalResource.java
  src/main/java/com/netgrif/application/engine/resource/domain/ExternalResourceLoader.java
  src/main/java/com/netgrif/application/engine/resource/service/ExternalResourceLoaderProcessor.java
Labels: new feature, Small

#245 [NAE-1927] Shared Roles
  docs/roles/shared_roles.md
  src/main/java/com/netgrif/application/engine/auth/web/responsebodies/ProcessRoleFactory.java
  src/main/java/com/netgrif/application/engine/importer/service/Importer.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/roles/ProcessRole.java
  src/main/java/com/netgrif/application/engine/petrinet/service/ProcessRoleService.java
Labels: Small

#249 [NAE-1952] Fix Loading Issue for Duplicate TaskRef Entries
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IDataService.java
Labels: bugfix, Extra Small
