Repository netgrif/application-engine, pull requests merged in 2024-04, with the labels that each got.

#255 [NAE-1959] Indexing enumerationMap field fails when no options exist
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseMappingService.java
Labels: Extra Small

#254 [NAE-1960] Enumeration Map does not propagate changes when selecting
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
Labels: Extra Small

#253 [NAE-1958] Make component properties changeable
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/java/com/netgrif/application/engine/petrinet/domain/Transition.java
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IDataService.java
  src/test/groovy/com/netgrif/application/engine/workflow/DataServiceTest.groovy
  src/test/resources/test_setData.xml
Labels: Large

#257 [NAE-1967] Elasticsearch disable dynamic field mapping
  src/main/java/com/netgrif/application/engine/configuration/properties/ElasticsearchProperties.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticIndexService.java
  src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticIndexService.java
  src/main/resources/elastic/default_analyzer.json
  src/main/resources/elastic/default_analyzer_ngram.json
Labels: bugfix
