Repository netgrif/application-engine, pull requests merged in 2024-02, with the labels that each got.

#196 [NAE-1876] Process URI v2
  src/main/groovy/com/netgrif/application/engine/migration/ActionMigration.groovy
  src/main/groovy/com/netgrif/application/engine/startup/ElasticsearchRunner.groovy
  src/main/groovy/com/netgrif/application/engine/startup/ImportHelper.groovy
  src/main/java/com/netgrif/application/engine/configuration/ElasticsearchConfiguration.java
  src/main/java/com/netgrif/application/engine/elastic/domain/ElasticCase.java
  src/main/java/com/netgrif/application/engine/elastic/domain/ElasticPetriNet.java
  src/main/java/com/netgrif/application/engine/elastic/domain/ElasticPetriNetRepository.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseMappingService.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticIndexService.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticPetriNetMappingService.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticPetriNetService.java
  src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticCaseService.java
  src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticPetriNetMappingService.java
  src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticPetriNetService.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/PetriNet.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/UriNode.java
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetEventHandler.java
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/UriService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IPetriNetService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IUriService.java
  src/main/java/com/netgrif/application/engine/petrinet/web/PetriNetController.java
  src/main/java/com/netgrif/application/engine/workflow/domain/Case.java
  src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
  src/main/resources/application-dev.properties
  src/main/resources/application.properties
  src/test/groovy/com/netgrif/application/engine/TestHelper.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/dataset/DynamicChoicesTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/domain/dataset/DynamicEnumerationTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/service/PetriNetServiceTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/service/UriServiceTest.groovy
  src/test/groovy/com/netgrif/application/engine/workflow/WorkflowServiceTest.groovy
  src/test/java/com/netgrif/application/engine/importer/ConstructorAndDestructorTest.java
  src/test/java/com/netgrif/application/engine/importer/ImporterTest.java
  src/test/java/com/netgrif/application/engine/workflow/web/VariableArcsTest.java
  src/test/resources/application-test-ldap.properties
  src/test/resources/application-test.properties
Labels: improvement, Extra Large

#210 [NAE-1882] Filter folder process
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/groovy/com/netgrif/application/engine/startup/FilterRunner.groovy
  src/main/java/com/netgrif/application/engine/configuration/properties/UriProperties.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticPetriNetService.java
  src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticCaseService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/UriService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IUriService.java
  src/main/java/com/netgrif/application/engine/workflow/domain/menu/MenuItemBody.java
  src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IWorkflowService.java
  src/main/resources/petriNets/engine-processes/filter.xml
  src/main/resources/petriNets/engine-processes/org_group.xml
  src/main/resources/petriNets/engine-processes/preference_item.xml
  src/test/groovy/com/netgrif/application/engine/action/FilterApiTest.groovy
  src/test/groovy/com/netgrif/application/engine/action/MenuItemApiTest.groovy
  src/test/groovy/com/netgrif/application/engine/elastic/DataSearchRequestTest.groovy
  src/test/groovy/com/netgrif/application/engine/workflow/WorkflowServiceTest.groovy
  src/test/resources/petriNets/filter_api_test.xml
Labels: improvement, Extra Large

#209 [NAE-1901] Taskref rendering update
  CHANGELOG.md
  src/main/java/com/netgrif/application/engine/workflow/service/DataService.java
  src/main/java/com/netgrif/application/engine/workflow/service/TaskSearchService.java
  src/main/java/com/netgrif/application/engine/workflow/web/requestbodies/TaskSearchRequest.java
Labels: improvement, new feature, Extra Small

#223 [NAE-1908] switch UriNode to MongoDB
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/groovy/com/netgrif/application/engine/startup/ImportHelper.groovy
  src/main/java/com/netgrif/application/engine/petrinet/domain/PetriNet.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/UriNode.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/repository/UriNodeRepository.java
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/UriService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IPetriNetService.java
  src/main/java/com/netgrif/application/engine/workflow/domain/Case.java
  src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IWorkflowService.java
  src/test/groovy/com/netgrif/application/engine/action/MenuItemApiTest.groovy
  src/test/groovy/com/netgrif/application/engine/petrinet/service/UriServiceTest.groovy
  src/test/groovy/com/netgrif/application/engine/workflow/WorkflowServiceTest.groovy
  src/test/java/com/netgrif/application/engine/workflow/service/TaskServiceTest.java
Labels: improvement, Medium

#242 [NAE-1947] HistoryService findAllSetDataEventLogs is not working
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/ChangedField.groovy
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/ChangedFieldsTree.groovy
  src/main/java/com/netgrif/application/engine/petrinet/domain/dataset/logic/ChangedField.java
  src/main/java/com/netgrif/application/engine/workflow/domain/eventoutcomes/dataoutcomes/SetDataEventOutcome.java
  src/test/groovy/com/netgrif/application/engine/history/HistoryServiceTest.groovy
Labels: bugfix, Medium

#110 [NAE-1684] Frontend component for data field caseRef
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/java/com/netgrif/application/engine/petrinet/domain/Node.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/Place.java
  src/main/java/com/netgrif/application/engine/petrinet/web/responsebodies/PlaceImportReference.java
  src/main/java/com/netgrif/application/engine/petrinet/web/responsebodies/TransitionImportReference.java
Labels: new feature, Extra Small

#240 [NAE-1944] Server-side JavaScript Code Injection (SSJI)
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
  src/main/java/com/netgrif/application/engine/elastic/service/ElasticTaskService.java
  src/main/java/com/netgrif/application/engine/petrinet/domain/PetriNetSearch.java
  src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IPetriNetService.java
  src/main/java/com/netgrif/application/engine/petrinet/web/PetriNetController.java
  src/main/java/com/netgrif/application/engine/petrinet/web/PublicPetriNetController.java
  src/main/java/com/netgrif/application/engine/workflow/service/CaseSearchService.java
  src/main/java/com/netgrif/application/engine/workflow/service/ConfigurableMenuService.java
  src/main/java/com/netgrif/application/engine/workflow/service/TaskSearchService.java
  src/test/groovy/com/netgrif/application/engine/petrinet/service/PetriNetServiceTest.groovy
  src/test/resources/process_search_test.xml
Labels: critical, Large

#80 [NAE-1654] Find actions for Elasticsearch
  src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  src/main/java/com/netgrif/application/engine/elastic/web/requestbodies/CaseSearchRequest.java
  src/main/java/com/netgrif/application/engine/elastic/web/requestbodies/ElasticTaskSearchRequest.java
Labels: improvement, Medium

#244 [NAE-1948] Bugs after merge to 6.4.0
  src/main/groovy/com/netgrif/application/engine/startup/ElasticsearchRunner.groovy
  src/main/java/com/netgrif/application/engine/workflow/service/ConfigurableMenuService.java
  src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IConfigurableMenuService.java
Labels: bugfix, Extra Small
