Repository netgrif/application-engine, pull requests merged in 2025-09, with the labels that each got.

#353 [NAE-2201] Dashboard management missing permissions
  application-engine/src/main/resources/petriNets/engine-processes/dashboard_item.xml
  application-engine/src/main/resources/petriNets/engine-processes/dashboard_management.xml
Labels: bugfix, improvement, Medium

#343 [NAE-2177] New method to build FieldType from name
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/petrinet/domain/dataset/FieldType.java
Labels: bugfix, improvement, Small

#354 [NAE-2199] Force delete of processes
  application-engine/src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  application-engine/src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IPetriNetService.java
  application-engine/src/main/java/com/netgrif/application/engine/petrinet/web/PetriNetController.java
  application-engine/src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
  application-engine/src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
  application-engine/src/main/java/com/netgrif/application/engine/workflow/service/interfaces/ITaskService.java
  application-engine/src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IWorkflowService.java
Labels: improvement, Medium

#350 [NAE-2193] Assign all roles to admin users
  application-engine/src/main/java/com/netgrif/application/engine/startup/runner/SuperCreatorRunner.java
  application-engine/src/test/groovy/com/netgrif/application/engine/action/RemoveActionTest.groovy
  application-engine/src/test/groovy/com/netgrif/application/engine/export/service/ExportServiceTest.groovy
  application-engine/src/test/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FileFieldTest.groovy
  application-engine/src/test/groovy/com/netgrif/application/engine/petrinet/domain/dataset/FileListFieldTest.groovy
  application-engine/src/test/groovy/com/netgrif/application/engine/workflow/CaseSearchTest.groovy
  application-engine/src/test/groovy/com/netgrif/application/engine/workflow/UserRefsTest.groovy
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/auth/constants/UserConstants.java
  nae-user-ce/src/main/java/com/netgrif/application/engine/auth/service/UserServiceImpl.java
  nae-user-common/src/main/java/com/netgrif/application/engine/auth/repository/UserRepository.java
  nae-user-common/src/main/java/com/netgrif/application/engine/auth/service/UserService.java
Labels: improvement, Medium

#355 [NAE-2194] Global role creation fix
  application-engine/src/main/java/com/netgrif/application/engine/importer/service/Importer.java
  nae-user-ce/src/main/java/com/netgrif/application/engine/auth/service/UserServiceImpl.java
  nae-user-common/src/main/java/com/netgrif/application/engine/auth/repository/UserRepository.java
  nae-user-common/src/main/java/com/netgrif/application/engine/auth/service/UserService.java
Labels: bugfix, Medium

#351 [NAE-2186] PetriNet objects gRPC serialization
  application-engine/src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  nae-user-ce/src/main/java/com/netgrif/application/engine/auth/service/UserServiceImpl.java
  nae-user-common/src/main/java/com/netgrif/application/engine/auth/service/UserService.java
Labels: bugfix, improvement, Medium, Small

#345 [NAE-2173] Password change
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/auth/domain/AbstractUser.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/auth/domain/User.java
  nae-user-ce/src/main/java/com/netgrif/application/engine/auth/service/UserServiceImpl.java
  nae-user-common/src/main/java/com/netgrif/application/engine/auth/service/UserService.java
  nae-user-common/src/main/java/com/netgrif/application/engine/auth/web/responsebodies/User.java
Labels: improvement, new feature, Medium

#352 [NAE-2197] Elastic Mapping Fixes
  application-engine/src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseMappingService.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/elastic/domain/StringCollectionField.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/elastic/domain/BooleanField.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/elastic/domain/ElasticCase.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/elastic/domain/StringCollectionField.java
Labels: bugfix, improvement, Medium, Small

#357 [NAE-2202] Post test fixes
  application-engine/src/main/java/com/netgrif/application/engine/menu/services/MenuItemService.java
  application-engine/src/main/java/com/netgrif/application/engine/workflow/service/CaseEventHandler.java
  application-engine/src/main/java/com/netgrif/application/engine/workflow/service/WorkflowService.java
  application-engine/src/main/java/com/netgrif/application/engine/workflow/service/interfaces/IWorkflowService.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/workflow/domain/Case.java
Labels: bugfix, Medium

#359 [NAE-2211] Fix partial update for SecretString
  nae-user-ce/src/main/java/com/netgrif/application/engine/auth/service/RealmServiceImpl.java
Labels: bugfix, Medium

#361 [NAE-2214] Add configuration option to disable plugin health check
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/plugin/domain/Plugin.java
Labels: improvement, Medium, Small

#362 [NAE-2213] Delete global role
  application-engine/src/main/java/com/netgrif/application/engine/importer/service/Importer.java
  application-engine/src/main/java/com/netgrif/application/engine/petrinet/config/ProcessBeansConfiguration.java
  application-engine/src/main/java/com/netgrif/application/engine/petrinet/domain/repositories/PetriNetRepository.java
  application-engine/src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  application-engine/src/main/java/com/netgrif/application/engine/petrinet/service/ProcessRoleService.java
  application-engine/src/main/java/com/netgrif/application/engine/petrinet/service/interfaces/IPetriNetService.java
  application-engine/src/main/java/com/netgrif/application/engine/petrinet/web/ProcessRoleController.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/petrinet/domain/PetriNetSearch.java
  nae-object-library/src/main/resources/petriflow_schema.xsd
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/petrinet/domain/roles/RoleNotFoundException.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/petrinet/domain/roles/RoleNotGlobalException.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/petrinet/domain/roles/RoleReferencedException.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/petrinet/service/ProcessRoleService.java
Labels: improvement, Medium
