Repository netgrif/application-engine, pull requests merged in 2025-05, with the labels that each got.

#301 [NAE-2093] Remove dependency on plugin-core
  application-engine/pom.xml
  application-engine/src/main/groovy/com/netgrif/application/engine/integration/plugin/injector/PluginHolder.groovy
  application-engine/src/main/groovy/com/netgrif/application/engine/integration/plugin/injector/PluginInjector.groovy
  application-engine/src/main/groovy/com/netgrif/application/engine/integration/plugin/injector/meta/EntryPointMeta.groovy
  application-engine/src/main/groovy/com/netgrif/application/engine/integration/plugin/injector/meta/PluginMeta.groovy
  application-engine/src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  application-engine/src/main/java/com/netgrif/application/engine/integration/plugins/config/PluginEngineServicesConfiguration.java
  application-engine/src/main/java/com/netgrif/application/engine/integration/plugins/exceptions/IncompatibleClassLoaderException.java
  application-engine/src/main/java/com/netgrif/application/engine/integration/plugins/exceptions/IncompatiblePluginException.java
  application-engine/src/main/java/com/netgrif/application/engine/integration/plugins/exceptions/InvalidRequestException.java
  application-engine/src/main/java/com/netgrif/application/engine/integration/plugins/exceptions/PluginDoesNotExistException.java
  application-engine/src/main/java/com/netgrif/application/engine/integration/plugins/exceptions/PluginIsAlreadyActiveException.java
  application-engine/src/main/java/com/netgrif/application/engine/integration/plugins/exceptions/RestrictedPackageException.java
  application-engine/src/main/java/com/netgrif/application/engine/integration/plugins/properties/PluginConfigProperties.java
  application-engine/src/main/java/com/netgrif/application/engine/integration/plugins/security/PluginSecurityConfiguration.java
  application-engine/src/main/java/com/netgrif/application/engine/integration/plugins/security/PluginSecurityPolicy.java
  application-engine/src/main/java/com/netgrif/application/engine/integration/plugins/service/PluginServiceImpl.java
  application-engine/src/main/java/com/netgrif/application/engine/integration/plugins/utils/PluginConstants.java
  application-engine/src/main/java/com/netgrif/application/engine/integration/plugins/utils/PluginUtils.java
  application-engine/src/main/java/com/netgrif/application/engine/startup/runner/PluginRunner.java
Labels: update

#298 [NAE-2076] Usage metrics
  application-engine/src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/FieldActionsRunner.groovy
  application-engine/src/main/java/com/netgrif/application/engine/event/dispatchers/ActionDispatcher.java
  application-engine/src/main/java/com/netgrif/application/engine/impersonation/service/ImpersonationService.java
  application-engine/src/main/resources/logback.xml
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/event/RunPhase.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/event/events/Event.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/event/events/event/ActionEvent.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/event/events/event/ActionStartEvent.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/event/events/event/ActionStopEvent.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/event/events/user/ImpersonationEvent.java
Labels: improvement

#305 [NAE-2099] MenuItemService.appendChildCaseIdInDataSet not setting hasChildren correctly
  src/main/java/com/netgrif/application/engine/menu/services/MenuItemService.java
Labels: bugfix

#314 [NAE-2115] Task search on Search Node
  application-engine/src/main/java/com/netgrif/application/engine/workflow/service/TaskService.java
  application-engine/src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/Task.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/elastic/domain/ElasticCase.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/elastic/domain/ElasticTask.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/workflow/domain/Task.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/elastic/domain/ElasticCase.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/elastic/domain/ElasticTask.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/workflow/domain/Task.java
Labels: Small
