Repository netgrif/application-engine, pull requests merged in 2025-08, with the labels that each got.

#334 [NAE-2147] Merge 6.5.0 into 7.0.0
  application-engine/src/main/groovy/com/netgrif/application/engine/startup/ImportHelper.groovy
  application-engine/src/main/java/com/netgrif/application/engine/importer/service/Importer.java
  application-engine/src/main/java/com/netgrif/application/engine/menu/services/DashboardManagementServiceImpl.java
  application-engine/src/main/java/com/netgrif/application/engine/menu/services/MenuItemService.java
  application-engine/src/main/java/com/netgrif/application/engine/petrinet/service/PetriNetService.java
  application-engine/src/main/java/com/netgrif/application/engine/startup/runner/DashboardManagementRunner.java
  application-engine/src/main/java/com/netgrif/application/engine/startup/runner/DashboardRunner.java
  application-engine/src/main/java/com/netgrif/application/engine/startup/runner/FilterRunner.java
  application-engine/src/main/java/com/netgrif/application/engine/startup/runner/MenuProcessRunner.java
  application-engine/src/main/resources/application.yaml
  application-engine/src/main/resources/petriNets/engine-processes/dashboard_item.xml
  application-engine/src/test/groovy/com/netgrif/application/engine/TestHelper.groovy
  application-engine/src/test/groovy/com/netgrif/application/engine/action/MenuItemApiTest.groovy
  application-engine/src/test/groovy/com/netgrif/application/engine/filters/FilterImportExportTest.groovy
  application-engine/src/test/groovy/com/netgrif/application/engine/petrinet/domain/EventTest.groovy
  application-engine/src/test/groovy/com/netgrif/application/engine/petrinet/domain/PetriNetTest.groovy
  application-engine/src/test/resources/net_clone2.xml
  application-engine/src/test/resources/net_clone3.xml
  application-engine/src/test/resources/net_import_2.xml
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/petrinet/domain/version/Version.java
Labels: improvement, Medium, Small

#330 [NAE-2153] Mongo indexation
  application-engine/pom.xml
  application-engine/src/main/java/com/netgrif/application/engine/configuration/MongoIndexesConfigurator.java
  application-engine/src/main/java/com/netgrif/application/engine/configuration/properties/DataConfigurationProperties.java
  application-engine/src/main/java/com/netgrif/application/engine/startup/runner/MongoDbRunner.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/annotations/Indexed.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/auth/domain/User.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/workflow/domain/Case.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/workflow/domain/Task.java
  nae-spring-core-adapter/pom.xml
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/configuration/AbstractMongoIndexesConfigurator.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/petrinet/domain/PetriNet.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/workflow/domain/Case.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/workflow/domain/Task.java
  nae-user-ce/src/main/java/com/netgrif/application/engine/auth/service/RealmServiceImpl.java
Labels: improvement, Medium

#317 [NAE-2118] Implement OpenID Connector Auth for Admin node
  nae-user-ce/src/main/java/com/netgrif/application/engine/auth/service/RealmServiceImpl.java
  nae-user-ce/src/main/java/com/netgrif/application/engine/auth/service/UserServiceImpl.java
  nae-user-common/src/main/java/com/netgrif/application/engine/auth/provider/AuthMethodProvider.java
  nae-user-common/src/main/java/com/netgrif/application/engine/auth/provider/ProviderRegistry.java
  nae-user-common/src/main/java/com/netgrif/application/engine/auth/service/RealmService.java
Labels: improvement, Extra Small

#338 [NAE-2170] FileField and FileListField does not work
  application-engine/src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/petrinet/domain/dataset/FileFieldValue.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/petrinet/domain/dataset/StorageField.java
Labels: bugfix, breaking change

#335 [NAE-2161] Optimize ElasticCaseService queries to eliminate maxClauseCount error
  application-engine/src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/service/ElasticTaskService.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/service/ElasticViewPermissionService.java
  application-engine/src/main/java/com/netgrif/application/engine/workflow/service/CaseSearchService.java
Labels: improvement

#339 [NAE-2168] Optimize bulk index for elasticsearch in v7
  application-engine/src/main/java/com/netgrif/application/engine/configuration/ElasticsearchConfiguration.java
  application-engine/src/main/java/com/netgrif/application/engine/configuration/properties/DataConfigurationProperties.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/domain/ElasticCaseRepository.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/domain/ElasticPetriNetRepository.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/domain/ElasticTaskRepository.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseMappingService.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/service/ElasticIndexService.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/service/ElasticPetriNetService.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/service/ElasticTaskQueueManager.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/service/ElasticTaskService.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/service/ReindexingTask.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/service/interfaces/IElasticIndexService.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/web/ElasticController.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/web/requestbodies/IndexParams.java
  application-engine/src/main/java/com/netgrif/application/engine/workflow/web/responsebodies/Task.java
  application-engine/src/main/resources/petriNets/engine-processes/menu/menu_item.xml
  application-engine/src/test/groovy/com/netgrif/application/engine/auth/WorkflowAuthorizationServiceTest.groovy
  application-engine/src/test/groovy/com/netgrif/application/engine/elastic/DataSearchRequestTest.groovy
  application-engine/src/test/groovy/com/netgrif/application/engine/elastic/ElasticTaskTest.groovy
  application-engine/src/test/groovy/com/netgrif/application/engine/elastic/ReindexTest.groovy
  application-engine/src/test/groovy/com/netgrif/application/engine/filters/FilterImportExportTest.groovy
  application-engine/src/test/groovy/com/netgrif/application/engine/insurance/mvc/InsuranceTest.groovy
  application-engine/src/test/groovy/com/netgrif/application/engine/petrinet/domain/roles/ProcessRoleTest.groovy
  application-engine/src/test/groovy/com/netgrif/application/engine/petrinet/service/PetriNetServiceTest.groovy
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/elastic/domain/CaseField.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/elastic/domain/ElasticCase.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/elastic/domain/ElasticPetriNet.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/elastic/domain/ElasticTask.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/elastic/serializer/LocalDateTimeJsonDeserializer.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/elastic/serializer/LocalDateTimeJsonSerializer.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/event/events/task/IndexTaskEvent.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/event/events/workflow/IndexCaseEvent.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/elastic/domain/CaseField.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/elastic/domain/ElasticCase.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/elastic/domain/ElasticPetriNet.java
  nae-spring-core-adapter/src/main/java/com/netgrif/application/engine/adapter/spring/elastic/domain/ElasticTask.java
Labels: improvement, Large

#341 Refactor case search to replace `stringId` with `id`.
  application-engine/src/main/java/com/netgrif/application/engine/elastic/service/ElasticCaseService.java
  application-engine/src/main/java/com/netgrif/application/engine/elastic/web/requestbodies/CaseSearchRequest.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/elastic/domain/ElasticCase.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/elastic/domain/ElasticTask.java
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/elastic/domain/ImmediateField.java
Labels: bugfix, improvement, Large

#342 Remove custom serializers for startDate in ElasticTask
  src/main/java/com/netgrif/application/engine/elastic/domain/ElasticTask.java
Labels: bugfix, Extra Small

#346 [NAE-2184] Nullable object as serializable alternative to Optional
  application-engine/src/main/groovy/com/netgrif/application/engine/petrinet/domain/dataset/logic/action/ActionDelegate.groovy
  application-engine/src/main/java/com/netgrif/application/engine/configuration/groovy/GroovyShellConfiguration.java
  application-engine/src/main/resources/application.yaml
  nae-object-library/src/main/java/com/netgrif/application/engine/objects/utils/Nullable.java
Labels: improvement
